name: Run X Reply Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - name: Run bot
        env:
          X_APP_KEY:            ${{ secrets.X_APP_KEY }}
          X_APP_SECRET:         ${{ secrets.X_APP_SECRET }}
          X_ACCESS_TOKEN:       ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET:      ${{ secrets.X_ACCESS_SECRET }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          USERS:                0x_ultra,Talus_Labs,Cbb0fe
          USERS_IDS:            924134809,1912085033902616577,1703332734603591680
          MAX_CHARS:            220
          LANGS:                ru,en
          STYLE:                short, specific, a bit witty, 1 sentence
          FRESH_HOURS:          24
          MAX_PER_RUN:          2
          DRY_RUN:              false
        run: node bot.mjs
